### PR TITLE
Try to handle pdf files with invalid stream length

### PR DESCRIPTION
**Pull request by jlauu**

### CODE REVIEW

**Comment by kedder** [comment]
Ok, I think I see where this PR is coming from. Let's not merge it, the PR turns the correct code into the incorrect one. We should identify the root of the problem before fixing it.

**Comment by kedder** [comment]
Basically, the stream length is correct there. The stream itself is corrupted.

**Comment by kedder** [comment]
The problem is in `reportlab.pdfbase.acroform.AcroForm`:

```python
        template = '''<<
...
stream
%(stream)s
endstream
'''
        ...
        return template % vars()
```

`template` is a string, `stream` is bytes. So under python3 template gets populated with string representation of bytes, instead of actual bytes.

**Comment by jordanvance** [comment]
wrap it with six.binary_types?

**Pull request closed without merging**
